sonar.projectKey=guilhermetborges_test
sonar.organization=guilhermetborges
sonar.host.url=https://sonarcloud.io

sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.next/**,**/coverage/**,**/vendor/**,**/.env,**/.env.*,**/*.db
