from apps.ingestion.models import SourceType
from apps.ingestion.schemas import SourceRegistrySeed

DEFAULT_SOURCE_SEEDS: list[SourceRegistrySeed] = [
    SourceRegistrySeed(
        source_key="us_uscis_main",
        country_code="US",
        country_name="Estados Unidos",
        program_code="US_GENERAL_IMMIGRATION",
        program_name="US Immigration - Official Rules",
        source_type=SourceType.html,
        source_url="https://www.uscis.gov/",
        robots_url="https://www.uscis.gov/robots.txt",
        terms_url="https://www.uscis.gov/about-us/website-policies",
        schedule_cron="0 */12 * * *",
    ),
    SourceRegistrySeed(
        source_key="us_travel_state_visas",
        country_code="US",
        country_name="Estados Unidos",
        program_code="US_VISAS",
        program_name="US Visas - Dept. of State",
        source_type=SourceType.html,
        source_url="https://travel.state.gov/content/travel/en/us-visas.html",
        robots_url="https://travel.state.gov/robots.txt",
        schedule_cron="15 */12 * * *",
    ),
    SourceRegistrySeed(
        source_key="pt_aima",
        country_code="PT",
        country_name="Portugal",
        program_code="PT_AIMA_VISAS",
        program_name="Portugal Residence and Visa Rules",
        source_type=SourceType.html,
        source_url="https://aima.gov.pt/",
        robots_url="https://aima.gov.pt/robots.txt",
        schedule_cron="0 2 * * *",
    ),
    SourceRegistrySeed(
        source_key="py_migraciones",
        country_code="PY",
        country_name="Paraguai",
        program_code="PY_MIGRACIONES",
        program_name="Paraguai Migracoes Oficiais",
        source_type=SourceType.html,
        source_url="https://www.migraciones.gov.py/",
        robots_url="https://www.migraciones.gov.py/robots.txt",
        schedule_cron="20 2 * * *",
    ),
    SourceRegistrySeed(
        source_key="uk_gov_immigration",
        country_code="GB",
        country_name="Reino Unido",
        program_code="UK_VISAS_IMMIGRATION",
        program_name="UK Visas and Immigration",
        source_type=SourceType.html,
        source_url="https://www.gov.uk/browse/visas-immigration",
        robots_url="https://www.gov.uk/robots.txt",
        schedule_cron="35 2 * * *",
    ),
    SourceRegistrySeed(
        source_key="jp_mofa_visa",
        country_code="JP",
        country_name="Japao",
        program_code="JP_VISA_RULES",
        program_name="Japan Visa - MOFA",
        source_type=SourceType.html,
        source_url="https://www.mofa.go.jp/j_info/visit/visa/index.html",
        robots_url="https://www.mofa.go.jp/robots.txt",
        schedule_cron="50 2 * * *",
    ),
    SourceRegistrySeed(
        source_key="jp_isa_reference",
        country_code="JP",
        country_name="Japao",
        program_code="JP_IMMIGRATION_ISA",
        program_name="Japan Immigration Services Agency",
        source_type=SourceType.html,
        source_url="https://www.isa.go.jp/en/",
        robots_url="https://www.isa.go.jp/robots.txt",
        schedule_cron="10 3 * * *",
    ),
    SourceRegistrySeed(
        source_key="de_make_it_in_germany",
        country_code="DE",
        country_name="Alemanha",
        program_code="DE_WORK_IMMIGRATION",
        program_name="Make it in Germany",
        source_type=SourceType.html,
        source_url="https://www.make-it-in-germany.com/en/",
        robots_url="https://www.make-it-in-germany.com/robots.txt",
        schedule_cron="25 3 * * *",
    ),
    SourceRegistrySeed(
        source_key="de_bamf",
        country_code="DE",
        country_name="Alemanha",
        program_code="DE_BAMF_IMMIGRATION",
        program_name="BAMF Immigration Rules",
        source_type=SourceType.html,
        source_url="https://www.bamf.de/EN/",
        robots_url="https://www.bamf.de/robots.txt",
        schedule_cron="40 3 * * *",
    ),
    SourceRegistrySeed(
        source_key="es_inclusion_migraciones",
        country_code="ES",
        country_name="Espanha",
        program_code="ES_MIGRACIONES",
        program_name="Ministerio de Inclusion y Migraciones",
        source_type=SourceType.html,
        source_url="https://www.inclusion.gob.es/en/",
        robots_url="https://www.inclusion.gob.es/robots.txt",
        schedule_cron="55 3 * * *",
    ),
    SourceRegistrySeed(
        source_key="it_esteri_visti",
        country_code="IT",
        country_name="Italia",
        program_code="IT_VISTI_INGRESSO",
        program_name="Italia Visti e Ingresso",
        source_type=SourceType.html,
        source_url="https://www.esteri.it/en/servizi-consolari-e-visti/ingressosoggiornoinitalia/",
        robots_url="https://www.esteri.it/robots.txt",
        schedule_cron="10 4 * * *",
    ),
    SourceRegistrySeed(
        source_key="ca_ircc",
        country_code="CA",
        country_name="Canada",
        program_code="CA_IRCC_IMMIGRATION",
        program_name="IRCC Immigration Rules",
        source_type=SourceType.html,
        source_url="https://www.canada.ca/en/services/immigration-citizenship.html",
        robots_url="https://www.canada.ca/robots.txt",
        schedule_cron="25 4 * * *",
    ),
    SourceRegistrySeed(
        source_key="ar_migraciones",
        country_code="AR",
        country_name="Argentina",
        program_code="AR_MIGRACIONES",
        program_name="Argentina Migraciones",
        source_type=SourceType.html,
        source_url="https://www.argentina.gob.ar/interior/migraciones",
        robots_url="https://www.argentina.gob.ar/robots.txt",
        schedule_cron="40 4 * * *",
    ),
    SourceRegistrySeed(
        source_key="fr_france_visas",
        country_code="FR",
        country_name="Franca",
        program_code="FR_FRANCE_VISAS",
        program_name="France Visas Official Rules",
        source_type=SourceType.html,
        source_url="https://france-visas.gouv.fr/",
        robots_url="https://france-visas.gouv.fr/robots.txt",
        schedule_cron="55 4 * * *",
    ),
    SourceRegistrySeed(
        source_key="ie_immigration_service_delivery",
        country_code="IE",
        country_name="Irlanda",
        program_code="IE_ISD_IMMIGRATION",
        program_name="Immigration Service Delivery",
        source_type=SourceType.html,
        source_url="https://www.irishimmigration.ie/",
        robots_url="https://www.irishimmigration.ie/robots.txt",
        schedule_cron="10 5 * * *",
    ),
    SourceRegistrySeed(
        source_key="nl_ind",
        country_code="NL",
        country_name="Paises Baixos",
        program_code="NL_IND_IMMIGRATION",
        program_name="IND Immigration Rules",
        source_type=SourceType.html,
        source_url="https://ind.nl/en",
        robots_url="https://ind.nl/robots.txt",
        schedule_cron="25 5 * * *",
    ),
    SourceRegistrySeed(
        source_key="ch_sem",
        country_code="CH",
        country_name="Suica",
        program_code="CH_SEM_ENTRY",
        program_name="SEM Entry Requirements",
        source_type=SourceType.html,
        source_url="https://www.sem.admin.ch/sem/en/home/themen/einreise.html",
        robots_url="https://www.sem.admin.ch/robots.txt",
        schedule_cron="40 5 * * *",
    ),
    SourceRegistrySeed(
        source_key="be_dofi",
        country_code="BE",
        country_name="Belgica",
        program_code="BE_DOFI_IMMIGRATION",
        program_name="Belgium Immigration Office",
        source_type=SourceType.html,
        source_url="https://dofi.ibz.be/en",
        robots_url="https://dofi.ibz.be/robots.txt",
        schedule_cron="55 5 * * *",
    ),
]
